import 'package:flutter/widgets.dart';

class Strings {
  static const _en = {
    'app_title': 'InstaDAM',
    'login_title': 'InstaDAM - Login',
    'username_label': 'Username',
    'display_label': 'Display name (optional)',
    'password_label': 'Password',
    'remember': 'Remember me',
    'enter': 'Sign in / Register',
    'feed_no_posts': 'No posts yet. Create your first!',
    'create_post': 'Create Post',
    'comments': 'Comments',
    'profile': 'Profile',
    'settings': 'Settings',
    'dark_theme': 'Dark theme',
    'notifs': 'Notifications',
    'language': 'Language',
    'logout': 'Log out',
    'logout_title': 'Log out',
    'logout_confirm': 'Are you sure you want to log out?',
    'add_comment': 'Add comment',
    'publish': 'Publish',
    'edit_name': 'Edit name',
    'cancel': 'Cancel',
    'save': 'Save',
    'delete_post': 'Delete Post',
    'delete_confirm': 'Are you sure you want to delete this post?',
    'delete': 'Delete',
    'select_language': 'Select Language',
    'appearance': 'Appearance & Accessibility',
    'notifications_section': 'Notifications',
    'info_section': 'Information',
    'about': 'About InstaDAM',
    'help': 'Help & Support',
    'activated': 'Activated',
    'disabled': 'Disabled',
    'notif_on': 'Notifications activated',
    'notif_off': 'Notifications deactivated',
    'back_tooltip': 'Back to previous screen',
    'edit_description': 'Edit description',
    'post_options': 'Post options',
    'like_active': 'Unlike. {count} people liked this',
    'like_inactive': 'Like. {count} people liked this',
    'likes_visual': '{count} Likes',
    'comment_accessible': 'Comment. {count} comments',
    'save_active': 'Remove from saved',
    'save_inactive': 'Save post',
    'view_comments': 'View all {count} comments',
    'nav_home': 'Home',
    'nav_messages': 'Messages',
    'nav_create': 'Create',
    'nav_reels': 'Reels',
    'nav_profile': 'Profile',
    'stat_posts': 'Posts',
    'stat_followers': 'Followers',
    'stat_following': 'Following',
    'edit_profile': 'Edit Profile',
    'grid_view': 'Grid view',
    'tagged_view': 'Photos of you',
    'dark_mode_tooltip': 'Dark mode',
    'light_mode_tooltip': 'Light mode',
    'no_account': 'Don\'t have an account? ',
    'register_now': 'Register.',
    'wrong_pass': 'Wrong password',
    'error_generic': 'An error occurred. Try again.',
    'empty_user_error': 'Username cannot be empty',
    'empty_pass_error': 'Password cannot be empty',
    'description_label': 'Write a description...',
    'location_label': 'Add location',
  };

  static const _es = {
    'app_title': 'InstaDAM',
    'login_title': 'InstaDAM - Login',
    'username_label': 'Nombre de usuario',
    'display_label': 'Nombre para mostrar (opcional)',
    'password_label': 'Contraseña',
    'remember': 'Recordarme',
    'enter': 'Entrar / Registrar',
    'feed_no_posts': 'Aún no hay posts. ¡Crea el primero!',
    'create_post': 'Crear Post',
    'comments': 'Comentarios',
    'profile': 'Perfil',
    'settings': 'Ajustes',
    'dark_theme': 'Tema oscuro',
    'notifs': 'Notificaciones',
    'language': 'Idioma',
    'logout': 'Cerrar sesión',
    'logout_title': 'Cerrar sesión',
    'logout_confirm': '¿Estás seguro de que quieres cerrar sesión?',
    'add_comment': 'Añadir comentario',
    'publish': 'Publicar',
    'edit_name': 'Editar nombre',
    'cancel': 'Cancelar',
    'save': 'Guardar',
    'delete_post': 'Eliminar publicación',
    'delete_confirm': '¿Estás seguro de que quieres eliminar esta publicación?',
    'delete': 'Eliminar',
    'select_language': 'Seleccionar idioma',
    'appearance': 'Apariencia y Accesibilidad',
    'notifications_section': 'Notificaciones',
    'info_section': 'Información',
    'about': 'Acerca de InstaDAM',
    'help': 'Ayuda y soporte técnico',
    'activated': 'Activado',
    'disabled': 'Desactivado',
    'notif_on': 'Notificaciones activadas',
    'notif_off': 'Notificaciones desactivadas',
    'back_tooltip': 'Volver a la pantalla anterior',
    'edit_description': 'Editar descripción',
    'post_options': 'Opciones de publicación',
    'like_active': 'Quitar me gusta. A {count} personas les gusta esto',
    'like_inactive': 'Me gusta. A {count} personas les gusta esto',
    'likes_visual': '{count} Me gusta',
    'comment_accessible': 'Comentar. {count} comentarios',
    'save_active': 'Quitar de guardados',
    'save_inactive': 'Guardar publicación',
    'view_comments': 'Ver los {count} comentarios',
    'nav_home': 'Inicio',
    'nav_messages': 'Mensajes',
    'nav_create': 'Crear',
    'nav_reels': 'Reels',
    'nav_profile': 'Perfil',
    'stat_posts': 'Publicaciones',
    'stat_followers': 'Seguidores',
    'stat_following': 'Seguidos',
    'edit_profile': 'Editar perfil',
    'grid_view': 'Vista de cuadrícula',
    'tagged_view': 'Fotos en las que apareces',
    'dark_mode_tooltip': 'Modo oscuro',
    'light_mode_tooltip': 'Modo claro',
    'no_account': '¿No tienes cuenta? ',
    'register_now': 'Regístrate.',
    'wrong_pass': 'Contraseña incorrecta',
    'error_generic': 'Ha ocurrido un error. Inténtalo de nuevo.',
    'empty_user_error': 'El nombre de usuario no puede estar vacío',
    'empty_pass_error': 'La contraseña no puede estar vacía',
    'description_label': 'Escribe una descripción...',
    'location_label': 'Añadir ubicación',
  };

  static String t(BuildContext context, String key, {Map<String, String>? args}) {
    final code = Localizations.localeOf(context).languageCode;
    String text = (code == 'en') ? (_en[key] ?? key) : (_es[key] ?? key);
    
    if (args != null) {
      args.forEach((k, v) {
        text = text.replaceAll('{$k}', v);
      });
    }
    return text;
  }
}
